version: "3.8"

services:
#  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
#    image: localstack/localstack
#    ports:
#      - "4566:4566"  # LocalStack Gateway
#      - "8082:8082"  # External services port range
#    environment:
#      - SERVICES=s3
#      - HOSTNAME_EXTERNAL=localhost
#      - PORT_WEB_UI=8082
#      - DEBUG=1
#      - ENABLE_WEB_UI=1
#      - LAMBDA_EXECUTOR=docker
#      - LOCALSTACK_API_KEY=6Mwv2N3lU9
  #  postgres:
#    container_name: database-lakeside-hotel
#    image: postgres:16.1
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: lakeside_hotel
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 5612

  lakeSideHotel:
    container_name: lakeside-hotel
    image: openjdk:17-jdk-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9192:9192"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://dpg-cnmtij021fec739906eg-a.singapore-postgres.render.com/lakeside_hotel_wst8"
#      SPRING_DATASOURCE_USERNAME: tripleng
#      SPRING_DATASOURCE_PASSWORD: VEaWB47dyqEZxCeKpeXpyVcnB5WWf7ZQ
#      AWS_REGION: "us-east-1"
#      S3_BUCKET_NAME: "lakeside-hotel"
#    depends_on:
#      - localstack
#    command: ["sh", "-c", "while ! pg_isready -U postgres; do sleep 5; done && java -likeSide-hotel-0.0.1-SNAPSHOT.jar"]
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

