#server:
#  port: 9192
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tripleng0801@gmail.com
    password: trnnqtrrkjmywljz
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: tripleng
    password: VEaWB47dyqEZxCeKpeXpyVcnB5WWf7ZQ
    url: jdbc:postgresql://dpg-cnmtij021fec739906eg-a.singapore-postgres.render.com/lakeside_hotel_wst8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework:
#        security: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
security:
  jwt:
    expire-length: 3600000
    secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
dropbox:
  key:
    access-token: sl.BxSSawHEHqIGu0in2CrDE9GB9B6C44rMbmsWr2cBfSxluN0ldCXpO9A5xSCNFyeoH0oPgVLr-3XMlOagVAS82henF8HkHDJb3-8llIHWDJeDlF56ZXCKc9Ckojs4qi6euiyZFnQuXFfdG5dyY2zUcn4